# Generated by Django 5.2.8 on 2025-11-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Admin', max_length=100, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=5, verbose_name='Read Time (minutes)'),
        ),
    ]
