# Generated by Django 5.2.8 on 2025-11-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Página Sobre', 'verbose_name_plural': 'Página Sobre'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Postagem', 'verbose_name_plural': 'Postagens'},
        ),
        migrations.AddField(
            model_name='post',
            name='body_text',
            field=models.TextField(blank=True, editable=False, verbose_name='Conteúdo Texto'),
        ),
        migrations.AlterField(
            model_name='about',
            name='body_html',
            field=models.TextField(editable=False, verbose_name='Conteúdo HTML'),
        ),
        migrations.AlterField(
            model_name='about',
            name='body_markdown',
            field=models.TextField(verbose_name='Conteúdo Markdown'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='Sobre Mim', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Admin', max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_html',
            field=models.TextField(editable=False, verbose_name='Conteúdo HTML'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_markdown',
            field=models.TextField(verbose_name='Conteúdo Markdown'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/covers/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=5, verbose_name='Tempo de Leitura (minutos)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Rascunho'), ('PB', 'Publicado')], default='DF', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
